spring:
  server:
    port: 8080
  application:
    name: cloud_takeaway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 2222
    url: jdbc:mysql://120.78.166.85:3308/cloud_takeaway?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
myimages:
  path: C:\code\mycode\Java\2023\project\cloud_takeaway\src\main\resources\myimages\