// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/contacts.proto

package com.kc.proto3;

public interface PeopleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto3.PeopleInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *字段类型 字段名 = 字段唯一编号(给字段名起个唯一标识)
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *字段类型 字段名 = 字段唯一编号(给字段名起个唯一标识)
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <pre>
   *  repeated string phoneNumber = 3;
   *  message Phone{
   *    string number = 1;
   *  }
   * </pre>
   *
   * <code>repeated .phone.Phone phone = 3;</code>
   */
  java.util.List<com.kc.proto3.Phone> 
      getPhoneList();
  /**
   * <pre>
   *  repeated string phoneNumber = 3;
   *  message Phone{
   *    string number = 1;
   *  }
   * </pre>
   *
   * <code>repeated .phone.Phone phone = 3;</code>
   */
  com.kc.proto3.Phone getPhone(int index);
  /**
   * <pre>
   *  repeated string phoneNumber = 3;
   *  message Phone{
   *    string number = 1;
   *  }
   * </pre>
   *
   * <code>repeated .phone.Phone phone = 3;</code>
   */
  int getPhoneCount();
  /**
   * <pre>
   *  repeated string phoneNumber = 3;
   *  message Phone{
   *    string number = 1;
   *  }
   * </pre>
   *
   * <code>repeated .phone.Phone phone = 3;</code>
   */
  java.util.List<? extends com.kc.proto3.PhoneOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <pre>
   *  repeated string phoneNumber = 3;
   *  message Phone{
   *    string number = 1;
   *  }
   * </pre>
   *
   * <code>repeated .phone.Phone phone = 3;</code>
   */
  com.kc.proto3.PhoneOrBuilder getPhoneOrBuilder(
      int index);
}
