// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/phone.proto

package com.kc.proto3;

public interface PhoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:phone.Phone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
