// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/contacts.proto

package com.kc.contact2;

public interface ContactsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto3.Contacts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  java.util.List<com.kc.contact2.PeopleInfo> 
      getContactsList();
  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  com.kc.contact2.PeopleInfo getContacts(int index);
  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  int getContactsCount();
  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  java.util.List<? extends com.kc.contact2.PeopleInfoOrBuilder> 
      getContactsOrBuilderList();
  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  com.kc.contact2.PeopleInfoOrBuilder getContactsOrBuilder(
      int index);
}
