// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: start/contacts.proto

package com.kc.pb;

public interface PeopleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:start.PeopleInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *字段类型 字段名 = 字段唯一编号(给字段名起个唯一标识)
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *字段类型 字段名 = 字段唯一编号(给字段名起个唯一标识)
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();
}
