
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 2222
    url: jdbc:mysql://localhost:3306/java_gobang?characterEncoding=utf8&serverTimezone=UTC
    username: root

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ?? MyBatis SQL ??
logging:
  level:
    com:
      example:
        demo: debug

