spring:
# 配置数据源信息
      datasource:
  # 配置数据源类型
           type: com.zaxxer.hikari.HikariDataSource
  # 配置连接数据库信息
           driver-class-name:  com.mysql.cj.jdbc.Driver
           url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&useSSL=false
           username: root
           password: 2222

# 配置MyBatis日志
mybatis-plus:
     configuration:
          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
         # 配置MyBatis-Plus的主键策略 id-type: auto
          id-type: auto
       #配置类型别名
          #type-aliases-package:   com.kc.mybatis.pojo