server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 2222
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
       server-addr: localhost:8848 # nacos服务地址
mybatis:
  type-aliases-package: org.example.kc.model
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.kc: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka